version: '3.8'
services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - '8000:8000'
    command:
      - start #start the SurrealDB server
      - --log=trace #no idea what this does :(
      - --user=root #default user
      - --pass=root #default password
    volumes:
      - ./data:/data/
    restart: always
    